using System;
namespace OpenProject.Shared
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class RepositoryInfo
    {
        public static string GitHubOwner => "opf";
        public static string GitHubRepository => "BCFier";
    }
}